# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee306189acd0bc49748becc917c07ac5cbb3709a00188524a8e35ada4ee6bdf7c1abcf51e1f502b6a19c5e1a6201c8c59b8d0919098b56b8a8d035517bbcbd91

test:
  secret_key_base: 57fee33edbe347ce42812307dc264a0931430c898bb2a1ccae2c045a80b3ec0af1f03f0a02d41321a090de9433f2e488df107f788287bcc11ff7be01bedeb56b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
